[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
  NPM_FLAGS = "--no-optional"
  GO_VERSION = "1.21.0" 