[build]
  base = "."
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse" 